name: Build ubi-flask container
on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: [self-hosted, Linux, X64]
#     runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ubi-flask
      REGISTRY: ghcr.io/major
    steps:

      - name: Clone the repository
        uses: actions/checkout@v3

#       - name: Install Buildah
#         run: |
#           apt-get -y install buildah

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2.12
        with:
          image: my-new-image
          tags: v1 ${{ github.sha }}
          containerfiles: |
            ./Containerfile
